services:
  ########################
  # Third-party services #
  ########################
  temporal:
    image: temporalio/auto-setup:${TEMPORAL_VERSION:-latest}
    environment:
      DB: mysql8
      DB_PORT: 3306
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development-sql.yaml
      MYSQL_PWD: password
      MYSQL_SEEDS: temporal-mysql
      MYSQL_USER: root
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CLI_ADDRESS: temporal:7233
    depends_on:
      - temporal-mysql
    volumes:
      - ./dev/temporal:/etc/temporal/config/dynamicconfig
    ports:
      - 4101:7233

  temporal-mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 4102:3306

  temporal-ui:
    image: temporalio/ui:${TEMPORAL_UI_VERSION:-latest}
    environment:
      TEMPORAL_ADDRESS: temporal:7233
    depends_on:
      - temporal
    ports:
      - 4100:8080
