services:
  control-plane:
    build:
      context: .
      dockerfile: ./apps/node.Dockerfile
      target: dev
      args:
        APP: control-plane
    environment:
      NATS_URL: nats://nats:4222
      SOCKET_REDIS_URL: redis://redis:6379
      SOCKET_REDIS_ENABLED: "true"
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CONNECTION_TIMEOUT: 60s
    ports:
      - 9000:3000
    restart: on-failure
    volumes:
      - ./apps:/home/node/root/apps
    links:
      - nats
      - redis
      - temporal
    depends_on:
      - downloader
      - temporal-ui

  downloader:
    build:
      context: .
      dockerfile: ./apps/downloader/Dockerfile
      args:
        APP: downloader
    environment:
      NATS_URL: nats://nats:4222
      TEMPORAL_ADDRESS: temporal:7233
    restart: on-failure
    links:
      - nats
      - temporal
    depends_on:
      - temporal-ui
    develop:
      watch:
        - path: ./apps/downloader
          action: rebuild

  ########################
  # Third-party services #
  ########################
  nats:
    image: nats
    command: --cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222
    ports:
      - 4200:8222

  redis:
    image: redis:7-alpine
    restart: on-failure

  temporal:
    image: temporalio/auto-setup:${TEMPORAL_VERSION:-latest}
    environment:
      DB: mysql8
      DB_PORT: 3306
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development-sql.yaml
      MYSQL_PWD: password
      MYSQL_SEEDS: temporal-mysql
      MYSQL_USER: root
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CLI_ADDRESS: temporal:7233
    depends_on:
      - temporal-mysql
    volumes:
      - ./dev/temporal:/etc/temporal/config/dynamicconfig
    ports:
      - 4101:7233

  temporal-mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 4102:3306

  temporal-ui:
    image: temporalio/ui:${TEMPORAL_UI_VERSION:-latest}
    environment:
      TEMPORAL_ADDRESS: temporal:7233
    depends_on:
      - temporal
    ports:
      - 4100:8080
